---
- name: Create a directory and Download tomcat from url
  hosts: localhost

  tasks:
    - name: Create a directory
      file:
        path: /opt/tomcat
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Download tomcat from url
      get_url: 
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
        dest: /opt/tomcat
        mode: 0755
        owner: centos
        group: centos
